### ISSUE TITLE
CSP integration autoload bug

### ISSUE THREAD

**Issue by thijsbouwes** [dealer4dealer/woocommerce-xcore-plugin#25]
# Versions
- WP 6.3.1
- xCore Rest API extension 1.12.2
- Customer Specific Pricing for WooCommerce 4.6.6

# When does this bug occur
When fetching a product with `/wp-json/wc-xcore/v1/products/search?sku=skuOfProduct`, the `class-xcore.php` adds Csp data to the response when the plugin [customer-specific-pricing-for-woocommerce](https://github.com/dealer4dealer/woocommerce-xcore-plugin/blob/f65b0f6ce20e80628689313614e64fa2546367e6/includes/class-xcore.php#L148) is active. 

## This generates the following error
`Uncaught Error: Class 'CSPAPI\Includes\API\CspMappingsCustomerBased' not found in /pathToApp/public/wp-content/plugins/woocommerce-xcore-plugin-master/includes/class-xcore.php:369`. Apparently the autoloader can't find the CspMappingsCustomerBased class.

# The problem
The CspMappingsCustomerBased is loaded conditionally through `cspTextInitFunc()`, only when the `csp_api_status` is set to `enable`. When the api status is enabled CspApi class is contructed and the method `includeFiles()` is called which requires `/includes/csp-api/includes/api/class-csp-mappings-customer-based.php`.

# Solution
Add the following check `isset($cspSettings['csp_api_status']) && 'enable' == $cspSettings['csp_api_status']` or autoload the class by yourself. I don't know if the information is required in the API?

Another option is to enable `Enabling CSP API allows you to manage the CSP pricing rules using Woocommerce Rest API` in CSP. Would have been nice if this is documented in the docs.

![Screenshot 2023-10-06 at 3 29 16 PM](https://github.com/dealer4dealer/woocommerce-xcore-plugin/assets/12730631/d5de27b0-961e-416e-be0e-4a12395a3ced)
<img width="946" alt="Screenshot 2023-10-06 at 3 24 25 PM" src="https://github.com/dealer4dealer/woocommerce-xcore-plugin/assets/12730631/26142f74-caa7-4c15-bce5-f309dd74ee06">

**Comment by WillieHuizing** [comment]
Thank you for reporting the issue.
It has been addressed in the latest release.
